### ISSUE TITLE
Confusing Wording in Instructions

### ISSUE THREAD

**Issue by karen-olson** [learn-co-curriculum/phase-4-cookies-and-sessions-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/4324/assignments/127797?module_item_id=264356

### Concern

The instructions initially say "Each user can view a maximum of three articles before seeing the paywall."

Farther down, they say "If the user has viewed fewer than 3 pages, render a JSON response with the article data.
If the user has viewed 3 or more pages, render a JSON response including an error message, and a status code of 401 unauthorized."

This allows users to view a maximum of 2 articles before seeing a paywall, rather than 3 articles as the instructions initially stated. The tests are written so that users should be able to view 2 articles before seeing a paywall.

**Comment by ihollander** [comment]
Thanks for flagging this @karen-olson - we'll update the lesson and tests to match the deliverables!

**Comment by karen-olson** [comment]
Thank you!
